### ISSUE TITLE
Test for exponent == 0 not required

### ISSUE THREAD

**Issue by JoshOrndorff** [darlenefung/PowerFunction#2]
Your algorithm is designed very nicely. In fact it is so nice that you don't even have to treat exponent == 0 as a special case. when exponent == 0 your code just never enters the loop and 1 is returned correctly.

To be clear, what you submitted works perfectly. I just wanted to point out that it could  be even shorter because you started in a smart way.

**Comment by jorndorff** [comment]
I just realized the title of this issue isn't very clear. I was referring to the if statement in the iterative function checking whether exponent is 0.

The unit test case for exponent = 0 is very important, and you've correctly included it.
